import {ArrowUpRight,Plus,Command,Search,Layers,Sparkles,ArrowRight} from 'lucide-react';
const asset=(name:string)=>`/assets/${name}.webp`;
export default function ProjectVisual({kind}:{kind:string}){if(kind==='forme'||kind==='packaging')return <div className={`project-art art-${kind}`}><img src={asset('forme-skincare')} alt="Forme concept skincare packaging in warm ivory with orange details" loading="lazy" width="1536" height="1024"/>{kind==='forme'&&<span className="image-caption">FORME<span>Care, in its purest form.</span></span>}</div>;
if(kind==='modular')return <div className="project-art art-modular"><div className="concept-top"><b>modular®</b><span>FORM & FUNCTION</span><Plus size={14}/></div><div className="modular-type">Beyond<br/><em>the expected.</em></div><img src={asset('modular-sculpture')} alt="Original sculptural composition of interlocking black and metallic modules" loading="lazy" width="1536" height="1024"/><span className="mini-tag">An exploration of form. 001—026</span><span className="art-arrow"><ArrowUpRight size={25}/></span></div>;
if(kind==='commerce')return <div className="project-art art-commerce"><div className="commerce-browser"><div className="concept-top"><b>O / S</b><span>SHOP ALL &nbsp; ABOUT</span><span>BAG (0)</span></div><div className="commerce-layout"><div><span className="mini-label">SOUND, CONSIDERED.</span><h4>Less noise.<br/><em>More feeling.</em></h4><p>Objects of sound.<br/>Made for your everyday.</p><span className="mock-button">Find your frequency <ArrowUpRight size={12}/></span></div><img src={asset('headphones')} alt="Black studio headphones with a small orange detail" loading="lazy" width="1536" height="1024"/></div><div className="commerce-foot"><span>01 — THE EVERYDAY HEADPHONE</span><span>DESIGNED TO LISTEN.</span></div></div></div>;
if(kind==='signal')return <div className="project-art art-signal"><div className="signal-logo"><Command size={24}/> signal</div><h4>Less searching.<br/><em>More thinking.</em></h4><div className="signal-app"><aside><Command size={15}/><span>Workspace</span><span>⌕ &nbsp; Search</span><span>▦ &nbsp; Library</span><span>✧ &nbsp; Assistant</span></aside><div className="signal-main"><span className="signal-greeting">A little clarity.</span><h5>What’s on your mind?</h5><div className="signal-input">Ask anything <ArrowUpRight size={13}/></div><div className="signal-chips"><span>✧ Explore an idea</span><span>↗ Find a connection</span></div><div className="signal-notes"><span>RECENT THOUGHTS</span><b>Designing with intention <ArrowUpRight size={11}/></b><b>The shape of an idea <ArrowUpRight size={11}/></b><b>A better starting point <ArrowUpRight size={11}/></b></div></div></div><span className="signal-foot">YOUR SECOND BRAIN. A LITTLE CALMER.</span></div>;
if(kind==='margin')return <div className="project-art art-margin"><div className="concept-top"><b>margin.</b><span>ARCHITECTURE & PRACTICE</span></div><div className="margin-body"><span>( A PRACTICE IN PERSPECTIVE )</span><h4>Room<br/>to <em>think.</em></h4><div className="margin-bottom"><span>Spaces for life.<br/>Ideas for living.</span><ArrowUpRight size={42}/></div></div><div className="margin-rule"/></div>;
if(kind==='motion')return <div className="project-art art-motion"><div className="concept-top"><span>AN EXERCISE IN MOMENTUM</span><span>PLAY ↗</span></div><div className="motion-type">make<br/><em>your move.</em><span>↗</span></div><div className="motion-bottom"><span>FLOW STATE®</span><span>DESIGN IN MOTION — 2026</span></div></div>;
return <div className="project-art art-index"><div className="index-browser"><div className="concept-top"><b><Layers size={16}/> index</b><span>Product &nbsp; Resources</span><span>Get started ↗</span></div><h4>Good work starts<br/>with <em>clear thinking.</em></h4><p>A home for everything your team knows.</p><span className="mock-button">Meet your new workspace <ArrowRight size={11}/></span><div className="index-board"><span><Search size={12}/> Find a little clarity...</span><div><b><Layers/>Project library</b><b><Sparkles/>Fresh ideas</b><b><Command/>Team resources</b></div></div></div></div>}
