import {useRef,useState} from 'react';
import {ArrowUpRight,Box,PenTool,Code2,Layers,MousePointer2,ScanLine,ArrowRight,Check} from 'lucide-react';
import {Label} from './Common';
import {services} from '../data';
import ProjectVisual from './ProjectVisual';
function CommerceDemo(){const [variant,setVariant]=useState('Graphite');const [added,setAdded]=useState(false);return <div className="commerce-demo"><div className="concept-top"><b>O / S</b><span>PRODUCT STUDY / 003</span><span>Bag ({added?1:0})</span></div><img src="/assets/headphones.webp" alt="Objects of Sound concept headphones" loading="lazy" width="1536" height="1024"/><div className="product-info"><div><span className="mini-label">THE EVERYDAY COLLECTION</span><h4>Form 01 Headphones</h4><p>Sound, in its simplest form.</p></div><span>$240</span></div><div className="variant-row"><span>Finish: {variant}</span><div>{['Graphite','Warm ivory'].map(v=><button key={v} className={`swatch ${v==='Warm ivory'?'ivory':''} ${variant===v?'selected':''}`} onClick={()=>{setVariant(v);setAdded(false)}} aria-label={`Select ${v}`} aria-pressed={variant===v}/>)}</div></div><button className="demo-cart" onClick={()=>setAdded(!added)}>{added?'Added to concept bag':'Add to bag'}{added?<Check size={16}/>:<PlusIcon/>}</button><span className="demo-note">Interactive concept · No purchase will be made</span></div>}
function PlusIcon(){return <span>+</span>}
function ServicePanel({service,index}:{service:typeof services[number];index:number}){const visual=useRef<HTMLDivElement>(null);const move=(e:React.PointerEvent)=>{if(!visual.current||matchMedia('(prefers-reduced-motion: reduce)').matches||e.pointerType!=='mouse')return;const r=visual.current.getBoundingClientRect();visual.current.style.setProperty('--tilt-x',`${(e.clientY-r.top-r.height/2)/r.height*-4}deg`);visual.current.style.setProperty('--tilt-y',`${(e.clientX-r.left-r.width/2)/r.width*4}deg`);};return <article className={`service-panel service-${service.kind} reveal ${index%2?'reverse':''}`}><div className="service-copy"><div className="service-meta mono"><span>{service.number} / {service.kind==='commerce'?'SHOPIFY + ECOMMERCE':service.kind==='brand'?'BRANDING + VISUAL DESIGN':'WEB DESIGN + DEVELOPMENT'}</span><ArrowUpRight size={18}/></div><span className="service-lead"><span className="status-dot"/>{service.lead}</span><h3>{service.title}</h3><p>{service.description}</p><div className="service-tags">{service.items.map(t=><span key={t}>{t}</span>)}</div><a className="service-link" href="#pricing">Explore {service.kind==='brand'?'branding':service.kind==='commerce'?'Shopify':'web'} packages <ArrowRight size={16}/></a></div><div ref={visual} className="service-visual" onPointerMove={move} onPointerLeave={()=>{visual.current?.style.setProperty('--tilt-x','0deg');visual.current?.style.setProperty('--tilt-y','0deg')}}>{service.kind==='digital'?<div className="digital-composition"><div className="visual-browser"><div className="browser-chrome"><i/><i/><i/><span>modular.design / concept</span></div><ProjectVisual kind="modular"/></div><div className="floating-tag tag-code"><Code2 size={16}/> ENGINEERED TO FEEL.</div><div className="floating-tag tag-motion"><span className="status-dot"/> DESIGN + MOTION + CODE</div></div>:service.kind==='brand'?<div className="brand-composition"><img src="/assets/forme-skincare.webp" alt="Forme identity and packaging study" loading="lazy" width="1536" height="1024"/><div className="brand-type-card"><span>THE IDENTITY SYSTEM</span><strong>Ff.</strong><div><span>FORME</span><span>01—26</span></div></div><div className="brand-swatch-card"><i/><i/><i/><span>CONSIDERED IN EVERY DETAIL.</span></div></div>:<CommerceDemo/>}</div></article>}
const capabilities=[{icon:Box,title:'3D + Motion',copy:'Depth, movement, and a little unexpected delight.'},{icon:MousePointer2,title:'UI / UX',copy:'Useful experiences that feel effortless to navigate.'},{icon:PenTool,title:'Illustration',copy:'A distinct point of view, drawn into every detail.'},{icon:Code2,title:'Development',copy:'Considered design, faithfully brought to life.'},{icon:Layers,title:'Design Systems',copy:'A coherent foundation that grows with you.'},{icon:ScanLine,title:'Product Visualization',copy:'Making the intangible feel within reach.'}];
export default function Services(){return <section id="services" className="section services-section"><div className="center-heading reveal"><Label>SERVICES</Label><h2>Three disciplines.<br/><em>One studio.</em></h2><p>Design, development and brand systems<br/>built to work together.</p></div><div className="service-list">{services.map((s,i)=><ServicePanel key={s.kind} service={s} index={i}/>)}</div><div className="capabilities-intro reveal"><span className="mono">THE DETAILS MAKE THE DIFFERENCE.</span><p>And everything in between.</p></div><div className="capability-grid">{capabilities.map(c=><div className="capability reveal" key={c.title}><c.icon strokeWidth={1.3} size={25}/><div><h3>{c.title}</h3><p>{c.copy}</p></div></div>)}</div></section>}
