export const studio={email:'hello@modulelabs.design',whatsapp:'',instagram:'',linkedin:'',x:''};
export type Project={id:string;name:string;category:string;year:string;kind:string;size:string;description:string;deliverables:string[]};
export const projects:Project[]=[
{id:'modular',name:'Modular',category:'3D Website',year:'2026',kind:'modular',size:'large',description:'A study in digital form. An interactive exhibition concept that makes sculptural objects feel tangible through careful typography, space, and motion.',deliverables:['Art direction','Interactive design','3D / WebGL']},
{id:'forme',name:'Forme',category:'Brand Identity',year:'2026',kind:'forme',size:'medium',description:'A considered identity for a fictional skincare label. A quiet visual language that connects the wordmark, packaging, and everyday brand touchpoints.',deliverables:['Brand identity','Visual language','Art direction']},
{id:'signal',name:'Signal',category:'AI Web App',year:'2026',kind:'signal',size:'tall',description:'An AI workspace concept that brings research, ideas, and next steps together. Designed around clear information hierarchy and a calmer way to work.',deliverables:['Product strategy','UI / UX','Design system']},
{id:'objects',name:'Objects of sound',category:'Shopify Ecommerce',year:'2026',kind:'commerce',size:'wide',description:'A storefront concept for considered audio products. Rich product presentation, simple choices, and a direct route from discovery to cart.',deliverables:['Shopify design','Product experience','Commerce development']},
{id:'margin',name:'Margin',category:'Full Website',year:'2026',kind:'margin',size:'medium',description:'An editorial website concept for an independent architecture practice. A typographic system built to give projects and perspectives their own room.',deliverables:['Editorial direction','Website design','Frontend development']},
{id:'forme-pack',name:'The everyday ritual',category:'Packaging',year:'2026',kind:'packaging',size:'medium',description:'A tactile extension of the Forme concept. Packaging, labels, and a consistent product family designed to feel equally considered on a shelf or a screen.',deliverables:['Packaging system','Product mockups','Print applications']},
{id:'flow',name:'Flow state',category:'Motion Website',year:'2026',kind:'motion',size:'wide',description:'A typographic motion study about rhythm and momentum. Large expressive type pairs with a deliberately restrained animation system.',deliverables:['Motion direction','Typography','Web animation']},
{id:'index',name:'Index',category:'SaaS Landing Page',year:'2026',kind:'index',size:'medium',description:'A focused launch page concept for a team knowledge tool. Clear product storytelling, useful detail, and a confident, uncomplicated visual system.',deliverables:['Landing page','Product storytelling','Responsive development']}
];
export const services=[
{number:'01',title:'Digital Experiences',lead:'Led by Manav',description:'Design and development for brands that need more than a static website.',kind:'digital',items:['3D Animated Websites','Landing Pages','Full Website Development','AI SaaS Web Apps','Motion Design for Web','Interactive Product Experiences','Frontend Development','Web Animation','Responsive Development','Performance Optimization']},
{number:'02',title:'Brand Systems',lead:'Led by Nikita',description:'From identity to physical applications, we build brands that stay coherent wherever they appear.',kind:'brand',items:['Brand Identity','Visual Identity','Logo Systems','Packaging Design','Graphic Design','Product Mockups','Product Design','Campaign Visuals','Brand Guidelines','Social / Marketing Assets']},
{number:'03',title:'Commerce Experiences',lead:'Design + development',description:'Shopify stores designed and engineered to make products easier to discover, understand and buy.',kind:'commerce',items:['Shopify Store Design','Theme Customization','Theme Layout Changes','Custom Sections','Product Page Optimization','Collection Page Design','Shopify App Integrations','Conversion-Focused UI','Cart / Checkout Improvements','Subscription Integrations','Reviews / Loyalty Integrations','Email Capture','Upsell / Cross-sell Components','Shopify Speed Optimization','Mobile Commerce Optimization','Product Launch Pages','Analytics / Tracking Setup','Maintenance & Improvements']}
];
export type Plan={name:string;price:string;description:string;features:string[]};
export const pricing:Record<string,Plan[]>={
Web:[{name:'Launch',price:'$2,500',description:'A focused beginning. For your next launch or campaign.',features:['1–2 pages','Custom UI','Responsive development','Basic motion','Core interactions','Performance pass','Deployment']},{name:'Growth',price:'$5,500',description:'A complete marketing website, with room to grow.',features:['Up to 6–7 pages','Custom UX/UI','Motion system','Responsive development','CMS integration where needed','Basic analytics','Performance optimization','Deployment']},{name:'Signature',price:'$10,000+',description:'For ideas that call for something extraordinary.',features:['10+ pages / custom scope','Full design system','Advanced motion','3D / WebGL','Custom frontend engineering','Integrations','Performance engineering','Launch support']}],
Branding:[{name:'Essential Identity',price:'$2,000+',description:'A clear, confident foundation for your brand.',features:['Logo direction','Typography','Color system','Core visual language','Basic brand guidelines']},{name:'Brand System',price:'$4,500+',description:'One coherent identity. Every point of contact.',features:['Brand strategy foundation','Full identity','Logo suite','Typography','Color system','Visual language','Social templates','Brand guidelines','Basic mockups']},{name:'Full Brand Experience',price:'$7,500+',description:'A brand that lives beautifully, on and off screen.',features:['Everything in Brand System','Packaging direction','Product mockups','Campaign visuals','Extended applications','Detailed brand guidelines','Launch asset system']}],
Shopify:[{name:'Store Refresh',price:'$2,500+',description:'A thoughtful next chapter for your existing store.',features:['Theme layout improvements','Homepage refinement','PDP optimization','Mobile improvements','Basic custom sections','App styling']},{name:'Growth Store',price:'$5,000+',description:'A distinctive shopping experience, built to grow.',features:['Custom storefront design','Homepage','PDP','Collection pages','Navigation','Cart improvements','App integrations','Responsive build','Performance pass']},{name:'Custom Commerce',price:'$9,000+',description:'Commerce built around the way your brand works.',features:['Full custom Shopify experience','Custom theme development','Advanced sections','Motion','Custom UX','Complex integrations','Subscription / loyalty / reviews','Conversion optimization','Performance engineering']}]
};
export const faqs=[
{q:'What kinds of projects does Module Labs take on?',a:'We work across digital experiences, brand systems, and Shopify commerce. That can mean a focused launch page, a full website, a new identity, or an interactive product experience. Tell us what you have in mind and we’ll help define the right scope.'},
{q:'Do you handle both design and development?',a:'Yes. We take projects from the first visual direction through design, development, and launch. Manav leads digital design and engineering, and Nikita leads brand and visual design. You can also bring us in for one part of a project.'},
{q:'How long does a website project usually take?',a:'The timeline depends on the scope, content, and complexity. A focused landing page takes less time than a complete website with custom motion or 3D. We agree on a realistic schedule and review milestones before starting.'},
{q:'Can you work with our existing brand?',a:'Absolutely. We can work within your existing identity and guidelines, refine what you already have, or build a new system if the project calls for it. We’ll start by understanding what is working and what needs to evolve.'},
{q:'Do you create 3D and animated websites?',a:'Yes. We use motion, interaction, and lightweight 3D to give a website a distinctive feel. We also plan for performance, mobile devices, and reduced-motion preferences so the experience stays usable.'},
{q:'Can you customize an existing Shopify store?',a:'Yes. We can improve your theme, build custom sections, refine product and collection pages, style app integrations, and improve the mobile shopping experience. A full rebuild isn’t always necessary.'},
{q:'Do you work with agencies as a white-label partner?',a:'Yes. We can support agencies with design, frontend development, motion, 3D, and Shopify work. We’ll agree on responsibilities, communication, and how we fit into your team before the project begins.'},
{q:'How do payments and project milestones work?',a:'We agree on the scope, deliverables, payment schedule, and review milestones in the proposal before work starts. If the scope changes, we discuss the impact on cost and timing with you before moving ahead.'}
];
